### ISSUE TITLE
 plextraktsync without command is deprecated. Executing "plextraktsync sync"

### ISSUE THREAD

**Issue by NGDM** [linuxserver-labs/docker-plextraktsync#20]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lsio-labs-wide.png)](https://linuxserver.io)

------------------------------

## Expected Behavior
Use current and non-deprecated commands

## Current Behavior
Cron command uses the deprecated `plextraktsync` command instead of the correct command `plextraktsync sync`

## Steps to Reproduce

1. Run regular initiated container and wait for next cron run of sync

## Environment
**OS:** Ubuntu 24.04.1 LTS
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
```
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
```

## Command used to create docker container (run/create/compose/screenshot)
docker-compose.yml
```
services:
  plextraktsync:
    image: lscr.io/linuxserver-labs/plextraktsync:latest
    container_name: plextraktsync
    volumes:
      - '$DOCKERDIR/plextraktsync/config:/config:rw'
    networks:
        - myBridge
    environment:
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
      - UMASK=$UMASK
    restart: 'unless-stopped'
```

.env
```
DOCKER_GID=1000
DOCKER_UID=1000
UMASK=022
DOCKERDIR=home/ngdm/docker
```

## Docker logs

```
…
plextraktsync  | INFO     Websocket connected                                                    
plextraktsync  | WARNING  plextraktsync without command is deprecated. Executing "plextraktsync sync"                                                                  
plextraktsync  | INFO     PlexTraktSync [0.32.2]       
…
```
